# Generated by Django 4.0.4 on 2022-05-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_employeur/')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse_postale', models.CharField(blank=True, max_length=150, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('date_anniv', models.DateTimeField(blank=True, null=True)),
                ('num_urssaf', models.CharField(blank=True, max_length=13, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ass_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_enfant/')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('date_anniv', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('allergie', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.employeur')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
            },
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('filiation', models.CharField(blank=True, choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Grand-mère', 'Grand-mère'), ('Grand-père', 'Grand-père'), ('Tante', 'Tante'), ('Oncle', 'Oncle'), ('Amis de la famille', 'Amis de la famille'), ('Autres validé par la famille', 'Autres validé par la famille')], max_length=150, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.employeur')),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.enfant')),
            ],
            options={
                'verbose_name': 'Contact Urgence',
                'verbose_name_plural': 'Contacts Urgences',
            },
        ),
    ]
