# Generated by Django 4.0.4 on 2022-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='statut',
            field=models.CharField(blank=True, choices=[('En_cours', 'En_cours'), ('En_attente', 'En_attente'), ('Suspendu', 'Suspendu'), ('Terminé', 'Terminé')], max_length=150, null=True),
        ),
    ]
